@startuml

    class Member {

    }
    class BoardMember {

        }
    class Person {

            }
    class Event {

        }
    class Conference {

        }
    class BoardMeeting {

        }
    class Location {

        }
    class AAUOC{
    }

    Event <|-- Conference
    Event <|-- BoardMeeting

    Person  <|-- Member
    Member <|-- BoardMember

    Location -o AAUOC
    Event -o AAUOC
    Person -o AAUOC

    Location -- Event
    Member -- Event
    Person -- Conference
    BoardMember -- BoardMeeting

@enduml