@startuml

    class Member {
        e-mail : String
    }
    class BoardMember {
        }
    class Person {
        name : String
            }
    class Event {
        date: Date
        description: String
        assign(l: Location) : void
        }
    class Conference {
        max_attendees: Integer
        }
    class BoardMeeting {

        }
    class Location {
        description : String
        address: String
        }
    class AAUOC{
        newLocation(l: Location): void
        newEvent (e : Event): void
        newPerson (p: Person): void
        informEvent(e: Event): void
        register(m: Member, e: Event): void

    }

    Event <|-- Conference
    Event <|-- BoardMeeting

    Person  <|-- Member
    Member <|-- BoardMember

    Location "0..*" -o AAUOC
    Event "0..*" -o AAUOC
    Person "0..*" -o AAUOC

    Location "1" -- "0..*" Event : isLocated in
    Member "0..*" -- "0..*" Event : attendsTo
    Person "0..*" -- "0..*" Conference : attendsTo
    BoardMember "0..*" -- "0..*" BoardMeeting   : attendsTo

@enduml