@startuml

    class Member {
        e-mail : String
    }
    class BoardMember {
        }
    class Person {
        name : String
            }
    class Event {
        date: Date
        description: String
        assign(l: Location) : void
        }
    class Conference {
        max_attendees: Integer
        }
    class BoardMeeting {

        }
    class Location {
        description : String
        address: String
        }
    class AAUOC{
        newLocation(l: Location): void
        newEvent (e : Event): void
        newPerson (p: Person): void
        informEvent(e: Event): void
        register(m: Member, e: Event): void

    }

    Event <|-- Conference
    Event <|-- BoardMeeting

    Person  <|-- Member
    Member <|-- BoardMember

    Location -o AAUOC
    Event -o AAUOC
    Person -o AAUOC

    Location -- Event
    Member -- Event
    Person -- Conference
    BoardMember -- BoardMeeting

@enduml